### PR TITLE
added more field access functions

### PR DESCRIPTION
**Pull request by RCMast3r**
the message I am working on describing needed these because I ran out of fields.

Would there be a better way to handle this?

Thanks!

### CODE REVIEW

**Comment by arobenko** [comment]
I'll add the required functionality soon (within next couple of days). There is a bit of extra work required in addition to the suggested change. I'll introduce the change to the "develop" branch first. It will find its way to master in the next release.

Also, are you manually creating your messages or using [commsdsl](https://github.com/commschamp/commsdsl) code generators to do so?

**Comment by RCMast3r** [comment]
I am using the commsdsl code generators to handle it:

https://github.com/hytech-racing/vectornav_driver/blob/master/vn_driver_lib_gen.nix

**Comment by arobenko** [comment]
I noticed that your message fields are split into some logical grouping. Maybe as a workaround for the the encountered limitation and not to wait until the comms library update is officially released, consider to move these groups into separate global `<bundle>` fields and reference these bundles as stand-alone message fields:

```
<fields>
    <bundle name="MyGroup1">
        ....
    </bundle>
    <bundle name="MyGroup2">
        ...
    </bundle>
</fields>

<message ...>
    ...
    <ref field="MyGroup1" />
    <ref field="MyGroup2" />
</message>
```
It will reduce the actual number of the message members.
For the integration code there is going to be some extra field de-reference in the middle before the actual require field is accessed, but for the efficiency of the final binary code such change probably won't have any effect.

**Comment by arobenko** [comment]
The requested change has been implemented on "develop" branch. Please let me know if it works for you as expected. If it does I'll no an official patch release.

**Comment by arobenko** [comment]
Officially released in [v5.2.6](https://github.com/commschamp/comms/releases/tag/v5.2.6)

**Pull request closed without merging**
